# encoding: utf-8 
# usando python 3
# Apresentação em cores - Altere o programa da fotossíntese (001 Saída Simples/apresentacao.py) de forma que cada 
# página de texto seja mostrada com uma cor diferente. 
# Destaque palavras específicas do restante do texto com uma cor, como por exemplo, 
# "verde" na cor verde

import os
 
os.system('clear')
print('\x1b[0;30;42m')
print(" ___________________________________________ ")
print("|                                           |")
print("|                                           |")
print("|              FOTOSSÍNTESE                 |")
print("|                                           |")
print("|                                           |")
print(" ___________________________________________ ")
print("                                             ")
print('\x1b[0m')
input("")
os.system('clear')
print('\x1b[0;30;43m')
print("                                                   ")
print("                                                   ")
print("A água e os sais minerais absorvidos pelas raízes  ")
print("sobem através dos vasos lenhosos do caule e chegam ")
print("às folhas.                                         ")
print("                                                   ")
print("                                                   ")
print("                                                   ")
print('\x1b[0m')
input("")
os.system('clear')
print('\x1b[0;37;44m')
print("                                                   ")
print("                                                   ")
print("Nas folhas, existe uma substância verde, a clorofi-")
print("la, que absorve a energia luminosa do sol. Ao mesmo")
print("tempo, por meio dos estômatos presentes nas folhas,")
print("a planta absorve gás carbônico do ar.              ")
print("                                                   ")
print("                                                   ")
print('\x1b[0m')
input("")
os.system('clear')
print('\x1b[0;30;45m')
print("                                                   ")
print("                                                   ")
print("Usando a energia solar, o gás carbônico e o hidro- ")
print("gênio contido na água retirada do solo, após com-  ")
print("plicadas reações químicas, a planta produz açúcares")
print("(glicose).                                         ")
print("                                                   ")
print("                                                   ")
print('\x1b[0m')
input("")
os.system('clear')
print("FIM")